export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'


export const DELIVERER_CREATE_REQUEST = 'DELIVERER_CREATE_REQUEST'
export const DELIVERER_CREATE_SUCCESS = 'DELIVERER_CREATE_SUCCESS'
export const DELIVERER_CREATE_FAIL = 'DELIVERER_CREATE_FAIL'


export const DELIVERER_DETAIL_REQUEST = 'DELIVERER_DETAIL_REQUEST'
export const DELIVERER_DETAIL_SUCCESS = 'DELIVERER_DETAIL_SUCCESS'
export const DELIVERER_DETAIL_FAIL = 'DELIVERER_DETAIL_FAIL'


export const DELIVERER_UPDATE_REQUEST = 'DELIVERER_UPDATE_REQUEST'
export const DELIVERER_UPDATE_SUCCESS = 'DELIVERER_UPDATE_SUCCESS'
export const DELIVERER_UPDATE_FAIL = 'DELIVERER_UPDATE_FAIL'


export const AVAILABLE_UPDATE_REQUEST = 'AVAILABLE_UPDATE_REQUEST'
export const AVAILABLE_UPDATE_SUCCESS = 'AVAILABLE_UPDATE_SUCCESS'
export const AVAILABLE_UPDATE_FAIL = 'AVAILABLE_UPDATE_FAIL'


export const CHECK_ORDER_GIVEN_REQUEST = 'CHECK_ORDER_GIVEN_REQUEST'
export const CHECK_ORDER_GIVEN_SUCCESS = 'CHECK_ORDER_GIVEN_SUCCESS'
export const CHECK_ORDER_GIVEN_FAIL = 'CHECK_ORDER_GIVEN_FAIL'


export const ORDER_STATUS_UPDATE_REQUEST = 'ORDER_STATUS_UPDATE_REQUEST'
export const ORDER_STATUS_UPDATE_SUCCESS = 'ORDER_STATUS_UPDATE_SUCCESS'
export const ORDER_STATUS_UPDATE_FAIL = 'ORDER_STATUS_UPDATE_FAIL'